steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/web-app:$SHORT_SHA'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/web-app:$SHORT_SHA'

- name: 'gcr.io/cloud-builders/gcloud'
  id: Clone TafariBeckford-GKE-Argo-CD repository
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    git clone https://github.com/TafariBeckford/GKE-Argo-CD.git && \
    cd GKE-Argo-CD && \
    git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)') \
    


- name: 'gcr.io/cloud-builders/gcloud'
  id: Generate Kubernetes manifest
  entrypoint: /bin/sh
  dir: manifest
  args:
  - '-c'
  - |
     sed -i 's/GOOGLE_CLOUD_PROJECT/${PROJECT_ID}/g' /manifest/kubernetes.yaml \
     sed -i 's/REPO_NAME/${_ARTIFACT_REPO}/g' /manifest/kubernetes.yaml \
     sed -i 's/COMMIT_SHA/${SHORT_SHA}/g' /manifest/kubernetes.yaml
     
- name: 'gcr.io/cloud-builders/gcloud'
  id: Push manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    cd GKE-Argo-CD && \
    git add kubernetes.yaml && \
    git commit -m "Deploying image us-central1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/webapp:${SHORT_SHA}
    Built from commit ${COMMIT_SHA} of repository TafariBeckford-GKE-Argo-CD
    Author: $(git log --format='%an <%ae>' -n 1 HEAD)" && \
    git push origin main

substitutions:
  _ARTIFACT_REPO: image-repository-876